"""fix

Revision ID: c2001dcc925a
Revises: a14dc9c71ab4
Create Date: 2025-03-25 00:56:04.832724

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c2001dcc925a"
down_revision: Union[str, None] = "a14dc9c71ab4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "user_id")
    op.add_column("users", sa.Column("email", sa.String(length=50), nullable=False))
    op.drop_column("users", "test_field")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "test_field", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "email")
    op.add_column(
        "reviews",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
