"""Initial migration

Revision ID: 55174d3b93cb
Revises:
Create Date: 2025-03-25 00:48:43.438366

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55174d3b93cb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("exam", sa.String(length=10), nullable=False),
        sa.Column("result", sa.Integer(), nullable=False),
        sa.Column("review", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("telephone", sa.String(length=15), nullable=False),
        sa.Column("password", sa.String(length=50), nullable=False),
        sa.Column("exam", sa.String(length=10), nullable=False),
        sa.Column("test_field", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("reviews")
    # ### end Alembic commands ###
