"""добавляю связь между таблицами

Revision ID: 450804bf2382
Revises: e14a318bcbaa
Create Date: 2025-03-25 01:04:40.415370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "450804bf2382"
down_revision: Union[str, None] = "e14a318bcbaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "reviews", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.drop_column("reviews", "user_id")
    # ### end Alembic commands ###
