"""Initial migration

Revision ID: a14dc9c71ab4
Revises: 55174d3b93cb
Create Date: 2025-03-25 00:51:13.968814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a14dc9c71ab4"
down_revision: Union[str, None] = "55174d3b93cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email")
    op.drop_column("users", "password")
    op.drop_column("users", "telephone")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "telephone", sa.VARCHAR(length=15), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "password", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column("email", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
