"""final fix(i think)

Revision ID: e14a318bcbaa
Revises: 6570ce7f5177
Create Date: 2025-03-25 01:01:42.570491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e14a318bcbaa"
down_revision: Union[str, None] = "6570ce7f5177"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telephone", sa.String(), nullable=False))
    op.add_column("users", sa.Column("email", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email")
    op.drop_column("users", "telephone")
    # ### end Alembic commands ###
