"""reformate tables

Revision ID: e4cf3e3aa7f8
Revises: ae888cc313f2
Create Date: 2025-04-14 20:40:14.054033

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4cf3e3aa7f8"
down_revision: Union[str, None] = "ae888cc313f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "reviews",
        sa.Column(
            "last_edit_time",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.add_column(
        "reviews", sa.Column("exam", sa.String(), nullable=False, server_default="ЕГЭ")
    )
    op.add_column(
        "reviews",
        sa.Column("result", sa.Integer(), nullable=False, server_default="97"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "result")
    op.drop_column("reviews", "exam")
    op.drop_column("reviews", "last_edit_time")
    # ### end Alembic commands ###
