""".

Revision ID: a78319057c69
Revises: 0f1496ec693c
Create Date: 2025-05-14 12:20:25.934912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a78319057c69"
down_revision: Union[str, None] = "0f1496ec693c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("slug", sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, "products", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="unique")
    op.drop_column("products", "slug")
    # ### end Alembic commands ###
