"""пытаюсь запустить эту адскую машину

Revision ID: f4b1e97b5398
Revises: c58505c27306
Create Date: 2025-03-25 00:13:34.793639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4b1e97b5398"
down_revision: Union[str, None] = "c58505c27306"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("reviews_user_id_fkey", "reviews", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "reviews_user_id_fkey", "reviews", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
