"""purchases

Revision ID: e4ff57fcbd77
Revises: fc66a1e71665
Create Date: 2025-05-09 19:26:44.100250

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4ff57fcbd77"
down_revision: Union[str, None] = "fc66a1e71665"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("purchases_product_id_fkey", "purchases", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "purchases_product_id_fkey", "purchases", "products", ["product_id"], ["id"]
    )
    # ### end Alembic commands ###
