"""reformate tables

Revision ID: c5d76eeb2698
Revises: 450804bf2382
Create Date: 2025-04-13 20:12:04.425937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5d76eeb2698"
down_revision: Union[str, None] = "450804bf2382"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "name")
    op.drop_column("reviews", "result")
    op.drop_column("reviews", "exam")
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(length=200), nullable=True)
    )
    op.create_unique_constraint(None, "users", ["email"])
    op.drop_column("users", "telephone")
    op.drop_column("users", "name")
    op.drop_column("users", "exam")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("exam", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("name", sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("telephone", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "hashed_password")
    op.add_column(
        "reviews",
        sa.Column("exam", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    )
    op.add_column(
        "reviews",
        sa.Column("result", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "reviews",
        sa.Column("name", sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
