"""fix

Revision ID: 6570ce7f5177
Revises: c2001dcc925a
Create Date: 2025-03-25 00:58:16.382671

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6570ce7f5177"
down_revision: Union[str, None] = "c2001dcc925a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
