""".

Revision ID: b56a0f028fc9
Revises: e4ff57fcbd77
Create Date: 2025-05-12 16:48:04.892467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b56a0f028fc9"
down_revision: Union[str, None] = "e4ff57fcbd77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("purchases", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.create_foreign_key(None, "purchases", "products", ["product_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "purchases", type_="foreignkey")
    op.alter_column("purchases", "email", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
