""".

Revision ID: c9bcac112ef3
Revises: 5ec1cfbcdbfb
Create Date: 2025-05-15 19:05:31.951935

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9bcac112ef3"
down_revision: Union[str, None] = "5ec1cfbcdbfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("product_slug", sa.String(length=100), nullable=False)
    )
    op.drop_constraint("payments_product_id_fkey", "payments", type_="foreignkey")
    op.create_foreign_key(None, "payments", "products", ["product_slug"], ["slug"])
    op.drop_column("payments", "product_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.create_foreign_key(
        "payments_product_id_fkey", "payments", "products", ["product_id"], ["id"]
    )
    op.drop_column("payments", "product_slug")
    # ### end Alembic commands ###
