"""reformate

Revision ID: 2fae4b0d951c
Revises: 9d2f1e042983
Create Date: 2025-05-08 22:08:02.692318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fae4b0d951c"
down_revision: Union[str, None] = "9d2f1e042983"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.create_unique_constraint(None, "users", ["telephone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###
