"""reformate

Revision ID: ce1dba3d6216
Revises: 518b16625c4c
Create Date: 2025-04-19 18:31:08.667728

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ce1dba3d6216"
down_revision: Union[str, None] = "518b16625c4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
