""".

Revision ID: 5ec1cfbcdbfb
Revises: a78319057c69
Create Date: 2025-05-15 16:55:41.427032

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ec1cfbcdbfb"
down_revision: Union[str, None] = "a78319057c69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone", sa.String(length=20), nullable=False))
    op.drop_constraint("users_telephone_key", "users", type_="unique")
    op.create_unique_constraint(None, "users", ["phone"])
    op.drop_column("users", "telephone")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "telephone", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.create_unique_constraint("users_telephone_key", "users", ["telephone"])
    op.drop_column("users", "phone")
    # ### end Alembic commands ###
