"""purchases

Revision ID: fc66a1e71665
Revises: 2fae4b0d951c
Create Date: 2025-05-09 19:10:13.200474

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fc66a1e71665"
down_revision: Union[str, None] = "2fae4b0d951c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("purchases", sa.Column("email", sa.String(), nullable=False))
    op.add_column("purchases", sa.Column("status", sa.String(), nullable=False))
    op.alter_column(
        "purchases",
        "paid_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "purchases",
        "paid_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_column("purchases", "status")
    op.drop_column("purchases", "email")
    # ### end Alembic commands ###
