"""reformate

Revision ID: 9d2f1e042983
Revises: 8034da554f29
Create Date: 2025-05-08 15:14:09.234219

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d2f1e042983"
down_revision: Union[str, None] = "8034da554f29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "users", "telephone", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "telephone", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###
