"""reformate

Revision ID: 8034da554f29
Revises: ce1dba3d6216
Create Date: 2025-04-20 17:34:30.570999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8034da554f29"
down_revision: Union[str, None] = "ce1dba3d6216"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("has_product_1", sa.Boolean(), nullable=False, default=False)
    )
    op.add_column(
        "users", sa.Column("has_product_2", sa.Boolean(), nullable=False, default=False)
    )
    op.add_column(
        "users", sa.Column("has_product_3", sa.Boolean(), nullable=False, default=False)
    )
    op.add_column(
        "users", sa.Column("has_product_4", sa.Boolean(), nullable=False, default=False)
    )
    op.add_column(
        "users", sa.Column("has_product_5", sa.Boolean(), nullable=False, default=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "has_product_5")
    op.drop_column("users", "has_product_4")
    op.drop_column("users", "has_product_3")
    op.drop_column("users", "has_product_2")
    op.drop_column("users", "has_product_1")
    # ### end Alembic commands ###
